POST http://localhost:3003/api/books
Content-Type: application/json

{
  "title": "The Romantic",
  "author": "William Boyd",
  "pages": 460,
  "yearPublished": 2022,
  "genreTag": 84
}

###
GET http://localhost:3003/api/books

###
POST http://localhost:3003/api/booklogs
Content-Type: application/json

{
  "book": "69939462595cbf801c77ce10",
  "date": "2025-01-01",
  "currentPage": "113"
}