const deweyTags = {
  10: 'Productivity & Self-Improvement',
  11: 'Health & Fitness',
  12: 'Food Writing',
  20: 'Life Advice',
  21: 'Memoir',
  22: 'Spirituality & Religion',
  23: 'Philosophy - metaphysics, ethics, language',
  30: 'General Science',
  31: 'Physics & Astronomy',
  32: 'Chemistry, Materials & Earth Sciences',
  33: 'Medicine & Psychiatry',
  34: 'Climate Science & Policy',
  35: 'Biology & Life Sciences',
  36: 'Outdoors, Wildlife & Plants',
  37: 'Natural History & Ecology',
  50: 'World History',
  51: 'Ancient & Classical History',
  52: 'Medieval & Modern History',
  53: 'Regional Histories',
  54: 'Contemporary History & Current Events',
  55: 'US & Global Politics',
  56: 'Dutch & European Politics',
  57: 'Activism & Political Practice',
  58: 'Essays & Political Philosophy',
  59: 'Debates, Political Issues & Political Science',
  60: 'Tech – meta & news',
  61: 'Tech – industry & Silicon Valley',
  62: 'Tech – AI',
  63: 'Tech – Ethics & Society',
  66: 'Software Engineering & Programming',
  67: 'Neuroscience',
  68: 'Mathematics & Computer Science',
  69: 'Engineering, Automotive & Space',
  70: 'Media & Journalism',
  71: 'Digital Culture',
  72: 'Trendwatching & Observational Culture',
  73: 'Music – artistic',
  74: 'Music – technical & industry',
  75: 'Global Cultures & Travel Writing',
  76: 'Culinary Culture',
  80: 'Books, Bookshops & Reading Life',
  81: 'Classic Literature',
  82: 'Fantasy & Science Fiction',
  83: 'Literary Fiction & Poetry',
  84: 'Historical Fiction & Literary Nonfiction',
  85: 'Romance',
  86: 'Genre Fiction',
  87: 'Anthologies, Short Stories & Essays',
  88: 'Mythology & Folklore',
  90: 'Arts',
  91: 'Photography',
  92: 'Design',
  93: 'Visual Art & Art Theory',
  94: 'Film & Theatre',
  95: 'Games',
};

export const deweyLabel = code => {
  const name = deweyTags[code];
  return name ? `${name} (${code})` : `${code}`;
};

export const deweyText = code => deweyTags[code] || code;

export default deweyTags;
